apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-qa
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: default
  source:
    path: qa
    repoURL: https://github.com/lordpangan/sample-kubevela-argocd.git
    targetRevision: HEAD